/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface DecimalOracleInterface extends utils.Interface {
  functions: {
    "decimal()": FunctionFragment;
    "getTokenValueOfEth(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "decimal" | "getTokenValueOfEth"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "decimal", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTokenValueOfEth",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "decimal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenValueOfEth",
    data: BytesLike
  ): Result;

  events: {};
}

export interface DecimalOracle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DecimalOracleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    decimal(overrides?: CallOverrides): Promise<[BigNumber]>;

    getTokenValueOfEth(
      ethOutput: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { tokenInput: BigNumber }>;
  };

  decimal(overrides?: CallOverrides): Promise<BigNumber>;

  getTokenValueOfEth(
    ethOutput: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    decimal(overrides?: CallOverrides): Promise<BigNumber>;

    getTokenValueOfEth(
      ethOutput: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    decimal(overrides?: CallOverrides): Promise<BigNumber>;

    getTokenValueOfEth(
      ethOutput: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    decimal(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTokenValueOfEth(
      ethOutput: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
